{% set sdata = load_setup_py_data() %}

package:
  name: pyviz_comms
  version: {{ sdata['version'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python setup.py --quiet install --single-version-externally-managed --record record.txt


requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pyviz_comms

about:
  home: www.holoviews.org
  summary: Bidirectional communication for PyViz
  license: BSD 3-Clause
